### ISSUE TITLE
Client sorting not working

### ISSUE THREAD

**Issue by missile-developer** [noxify/next-rsc-search#1]
I try to implement your data-table approach in my project, however I can't figure it out how to make client side sorting back to work.

Am I doing anything wrong? Please guiding me!

**Comment by noxify** [comment]
Hi @missile-developer ,

client sorting is/was not planned as it doesn't exist in the base repo: https://github.com/sadmann7/shadcn-table

Anyway... based on the tanstack table documentation:
https://tanstack.com/table/latest/docs/guide/sorting#client-side-vs-server-side-sorting

it could be enough to remove the sorting definitions here:
https://github.com/noxify/reactquerybuilder-nextjs-rsc-queryparams/blob/main/src/hooks/use-data-table.ts#L76-L106

Maybe it's enough to set 

``` 
manualSorting: false
```

If this does not work, I would remove all sort properties from the block linked above.
To ensure that your queries doesn't do any sorting, you should also update the definition here:
https://github.com/noxify/reactquerybuilder-nextjs-rsc-queryparams/blob/main/src/utils/tasks-data.ts#L29

Just remove the `orderBy` properties or set a default sorting.

Does this help?
